// Parameter model, slider definitions and preset catalogue.

export const NEUTRAL = {
  exposure: 0, contrast: 0, saturation: 0, vibrance: 0, temperature: 0, tint: 0,
  highlights: 0, shadows: 0, fade: 0, hueShift: 0, bleach: 0, mono: 0, filmic: 0,
  monoMix: [0.3, 0.59, 0.11],
  lift: [0, 0, 0], gamma: [0, 0, 0], gain: [0, 0, 0],
  shadowTint: [0, 0, 0], highTint: [0, 0, 0], splitAmt: 1, splitBalance: 0,
  gmDark: [0.1, 0.05, 0.2], gmMid: [0.5, 0.45, 0.45], gmLight: [1.0, 0.95, 0.85], gmAmt: 0,
  blurRadius: 0.02, glow: 0, glowThreshold: 0, glowMode: 0, glowTint: [1, 1, 1],
  halation: 0, clarity: 0, sharpen: 0, chromAb: 0,
  grain: 0, grainSize: 1.5, grainType: 0,
  vignette: 0, vignetteFeather: 0.5,
};

// Keys scaled by the master intensity slider (interpolated toward NEUTRAL).
export const LERP_KEYS = new Set([
  'exposure', 'contrast', 'saturation', 'vibrance', 'temperature', 'tint', 'highlights', 'shadows',
  'fade', 'hueShift', 'bleach', 'mono', 'filmic', 'lift', 'gamma', 'gain', 'shadowTint', 'highTint',
  'gmAmt', 'glow', 'halation', 'clarity', 'sharpen', 'chromAb', 'grain', 'vignette',
]);

export const CONTROL_DEFS = {
  exposure: { label: '露出', min: -2, max: 2, step: 0.01 },
  contrast: { label: 'コントラスト', min: -1, max: 1, step: 0.01 },
  saturation: { label: '彩度', min: -1, max: 1, step: 0.01 },
  vibrance: { label: '自然な彩度', min: -1, max: 1, step: 0.01 },
  temperature: { label: '色温度', min: -1, max: 1, step: 0.01 },
  tint: { label: '色かぶり (G/M)', min: -1, max: 1, step: 0.01 },
  highlights: { label: 'ハイライト', min: -1, max: 1, step: 0.01 },
  shadows: { label: 'シャドウ', min: -1, max: 1, step: 0.01 },
  fade: { label: 'フェード', min: 0, max: 0.6, step: 0.01 },
  hueShift: { label: '色相シフト', min: -180, max: 180, step: 1 },
  bleach: { label: 'ブリーチバイパス', min: 0, max: 1, step: 0.01 },
  mono: { label: 'モノクロ化', min: 0, max: 1, step: 0.01 },
  filmic: { label: 'フィルミック', min: 0, max: 1, step: 0.01 },
  splitAmt: { label: 'スプリットトーン', min: 0, max: 2, step: 0.01 },
  splitBalance: { label: 'トーンバランス', min: -1, max: 1, step: 0.01 },
  gmAmt: { label: 'グラデーションマップ', min: 0, max: 1, step: 0.01 },
  glow: { label: '発光/ぼかしの不透明度', min: 0, max: 1, step: 0.01 },
  blurRadius: { label: 'ぼかし半径', min: 0.002, max: 0.08, step: 0.001 },
  glowThreshold: { label: 'レベル補正(しきい値)', min: 0, max: 0.9, step: 0.01 },
  halation: { label: 'ハレーション', min: 0, max: 1, step: 0.01 },
  clarity: { label: '明瞭度', min: -1, max: 1, step: 0.01 },
  sharpen: { label: 'シャープ', min: 0, max: 1.5, step: 0.01 },
  chromAb: { label: '色収差 (RGBずらし)', min: 0, max: 2, step: 0.01 },
  grain: { label: 'ノイズ量', min: 0, max: 0.6, step: 0.01 },
  grainSize: { label: 'ノイズの粒サイズ', min: 0.5, max: 24, step: 0.1 },
  vignette: { label: '周辺減光', min: 0, max: 1, step: 0.01 },
  vignetteFeather: { label: '減光の広がり', min: 0, max: 1, step: 0.01 },
};

export const ADJUST_KEYS = [
  'exposure', 'contrast', 'highlights', 'shadows', 'temperature', 'tint',
  'saturation', 'vibrance', 'clarity', 'sharpen', 'fade', 'vignette', 'grain',
];

export const CATEGORIES = [
  { id: 'all', label: 'すべて' },
  { id: 'cinema', label: '映画' },
  { id: 'film', label: 'フィルム' },
  { id: 'camera', label: 'カメラアプリ' },
  { id: 'mono', label: 'モノクロ' },
  { id: 'illust', label: 'イラスト' },
];

const P = (id, name, cat, desc, params, controls) => ({ id, name, cat, desc, params, controls });

export const PRESETS = [
  P('none', 'オリジナル', 'all', '補正なし。「調整」タブの値のみ適用されます。', {}, []),

  // ---------------- 映画 (Cinema) ----------------
  P('teal_orange', 'Teal & Orange', 'cinema', 'ハリウッド映画の定番。シャドウをティール、肌やハイライトをオレンジに分離。',
    { shadowTint: [-0.09, 0.03, 0.10], highTint: [0.10, 0.03, -0.08], contrast: 0.15, vibrance: 0.2, saturation: 0.05 },
    ['splitAmt', 'splitBalance', 'contrast', 'vibrance']),
  P('bleach_bypass', 'Bleach Bypass', 'cinema', '銀残し。低彩度・高コントラストの硬質な質感。',
    { bleach: 0.85, saturation: -0.3, contrast: 0.15, grain: 0.08 },
    ['bleach', 'saturation', 'contrast', 'grain']),
  P('blockbuster_cool', 'Cool Steel', 'cinema', 'アクション映画の青みがかった冷たいルック。',
    { temperature: -0.3, shadowTint: [-0.04, 0.0, 0.09], highTint: [0.04, 0.02, -0.02], contrast: 0.2, saturation: -0.1 },
    ['temperature', 'splitAmt', 'contrast', 'saturation']),
  P('matrix', 'Matrix Green', 'cinema', 'シャドウとミッドに緑を乗せたデジタル世界のトーン。',
    { gain: [-0.06, 0.06, -0.06], shadowTint: [-0.02, 0.06, 0.0], saturation: -0.15, contrast: 0.15 },
    ['splitAmt', 'saturation', 'contrast']),
  P('mexico', 'Mexico Yellow', 'cinema', '黄色く焼けた乾いた空気感。暖色に寄せて彩度を少し落とす。',
    { temperature: 0.55, tint: -0.1, gain: [0.05, 0.02, -0.12], saturation: -0.05, contrast: 0.1 },
    ['temperature', 'contrast', 'saturation']),
  P('day_for_night', 'Day for Night', 'cinema', '昼間の撮影を夜に見せる擬似夜景。露出を落とし青に転がす。',
    { exposure: -1.1, temperature: -0.55, saturation: -0.35, shadowTint: [-0.02, 0.0, 0.08], contrast: 0.2, vignette: 0.3 },
    ['exposure', 'temperature', 'saturation', 'vignette']),
  P('cyberpunk', 'Cyberpunk Neon', 'cinema', 'マゼンタのシャドウとシアンのハイライト。色収差と発光で近未来感。',
    { shadowTint: [0.08, -0.04, 0.12], highTint: [-0.08, 0.06, 0.10], saturation: 0.3, contrast: 0.2, chromAb: 0.5, glow: 0.2, glowThreshold: 0.55, blurRadius: 0.03 },
    ['splitAmt', 'saturation', 'chromAb', 'glow', 'contrast']),
  P('golden_hour', 'Golden Hour', 'cinema', '夕暮れの柔らかな暖色光。ハイライトに淡いグローとハレーション。',
    { temperature: 0.35, highTint: [0.08, 0.04, -0.04], exposure: 0.15, glow: 0.15, glowThreshold: 0.5, blurRadius: 0.04, halation: 0.25, contrast: 0.05 },
    ['temperature', 'glow', 'halation', 'exposure']),
  P('moody_dark', 'Moody Dark', 'cinema', '暗く沈んだ低彩度のシネマティックなムード。',
    { exposure: -0.4, contrast: 0.2, saturation: -0.25, shadowTint: [-0.03, 0.0, 0.05], vignette: 0.35, fade: 0.1 },
    ['exposure', 'contrast', 'saturation', 'vignette', 'fade']),
  P('thriller_green', 'Thriller Green', 'cinema', 'サスペンス映画の緑がかった低彩度トーン。',
    { gain: [-0.03, 0.04, -0.02], saturation: -0.35, contrast: 0.25, vignette: 0.3, shadowTint: [0.0, 0.03, 0.0] },
    ['saturation', 'contrast', 'vignette']),
  P('pastel_wes', 'Pastel Symmetry', 'cinema', 'パステル調で軽やかな、フェードの効いた画面。',
    { fade: 0.25, saturation: 0.15, temperature: 0.15, contrast: -0.15, highTint: [0.05, 0.0, 0.02], tint: 0.05 },
    ['fade', 'saturation', 'temperature', 'contrast']),
  P('scifi_cold', 'Sci-Fi Cold', 'cinema', '冷たく硬い、無機質なSF映画のトーン。',
    { temperature: -0.4, tint: 0.05, contrast: 0.2, saturation: -0.1, sharpen: 0.3, shadowTint: [0.0, 0.02, 0.05] },
    ['temperature', 'contrast', 'sharpen', 'saturation']),
  P('anamorphic', 'Anamorphic Halation', 'cinema', 'ハイライトが赤く滲むフィルム的なハレーションと色収差。',
    { halation: 0.6, glow: 0.15, glowThreshold: 0.6, blurRadius: 0.035, chromAb: 0.3, vignette: 0.2, contrast: 0.1 },
    ['halation', 'glow', 'chromAb', 'vignette']),
  P('filmic_soft', 'Filmic Roll-off', 'cinema', 'ハイライトを柔らかくロールオフさせるフィルム的トーンカーブ。',
    { filmic: 0.8, saturation: 0.05, fade: 0.04 },
    ['filmic', 'saturation', 'fade']),

  // ---------------- フィルム (Film) ----------------
  P('portra', 'Portrait Film 400', 'film', '肌色が柔らかく写るネガフィルム風。低コントラスト・暖色。',
    { temperature: 0.15, saturation: -0.05, vibrance: 0.1, contrast: -0.05, fade: 0.08, highlights: -0.1, grain: 0.08, highTint: [0.03, 0.01, -0.02] },
    ['temperature', 'fade', 'grain', 'contrast']),
  P('velvia', 'Vivid Slide 50', 'film', '風景向けの高彩度リバーサル風。',
    { saturation: 0.35, vibrance: 0.2, contrast: 0.2, temperature: 0.05 },
    ['saturation', 'vibrance', 'contrast']),
  P('kodachrome', 'Classic Chrome 64', 'film', '赤が深く、青が沈むクラシックなリバーサル調。',
    { contrast: 0.2, saturation: 0.1, gain: [0.06, 0.0, -0.04], shadowTint: [-0.02, 0.0, 0.04], temperature: 0.1, grain: 0.06 },
    ['contrast', 'saturation', 'temperature', 'grain']),
  P('ektar', 'Ultra Color 100', 'film', '微粒子で発色の良いネガフィルム。シャープで鮮やか。',
    { saturation: 0.25, contrast: 0.15, temperature: 0.1, sharpen: 0.25, vibrance: 0.1 },
    ['saturation', 'contrast', 'sharpen']),
  P('cinestill', 'Tungsten 800T', 'film', 'タングステンフィルムを昼光で使った青みと、赤いハレーション。',
    { temperature: -0.35, tint: 0.08, halation: 0.7, shadowTint: [-0.04, 0.02, 0.06], grain: 0.15, contrast: 0.05, blurRadius: 0.025 },
    ['temperature', 'halation', 'grain', 'splitAmt']),
  P('superia', 'Everyday 400', 'film', '緑がかったシャドウの日常的なネガフィルム風。',
    { shadowTint: [-0.02, 0.04, 0.0], saturation: 0.1, fade: 0.05, temperature: -0.05, grain: 0.1 },
    ['saturation', 'fade', 'grain']),
  P('cross', 'Cross Process', 'film', 'クロスプロセス。黄色いハイライトと青緑のシャドウ、高コントラスト。',
    { lift: [-0.03, 0.03, 0.10], gain: [0.10, 0.06, -0.15], contrast: 0.3, saturation: 0.2 },
    ['contrast', 'saturation', 'splitAmt']),
  P('vintage', 'Faded Vintage', 'film', '色あせた古い写真。フェードと粒子、周辺減光。',
    { fade: 0.35, saturation: -0.25, temperature: 0.2, vignette: 0.3, grain: 0.15, contrast: -0.1, highTint: [0.04, 0.02, -0.02] },
    ['fade', 'saturation', 'vignette', 'grain']),
  P('expired', 'Expired Film', 'film', '期限切れフィルムのマゼンタかぶりと粗い粒子。',
    { tint: 0.25, fade: 0.2, saturation: -0.1, grain: 0.25, grainSize: 2, contrast: 0.05, lift: [0.03, 0.0, 0.03] },
    ['tint', 'fade', 'grain', 'grainSize']),
  P('instant', 'Instant Film', 'film', 'インスタントカメラ風。低コントラストで淡く、四隅が落ちる。',
    { fade: 0.2, temperature: 0.1, saturation: -0.1, contrast: -0.1, vignette: 0.25, gain: [0.0, 0.02, 0.03], exposure: 0.1 },
    ['fade', 'temperature', 'vignette', 'exposure']),

  // ---------------- カメラアプリ (Camera app) ----------------
  P('clarity_pop', 'Clarity Pop', 'camera', 'SNS定番の明瞭度アップ＋高彩度。シャドウを少し冷たく。',
    { clarity: 0.4, contrast: 0.15, saturation: 0.2, shadowTint: [-0.03, 0.0, 0.04], blurRadius: 0.03 },
    ['clarity', 'contrast', 'saturation']),
  P('warm_glow', 'Warm Glow', 'camera', '暖かい光と赤みの強いポートレート向けフィルター。',
    { temperature: 0.25, saturation: 0.2, gain: [0.05, 0.0, -0.02], contrast: 0.1, glow: 0.1, glowThreshold: 0.5, blurRadius: 0.04 },
    ['temperature', 'saturation', 'glow']),
  P('bright_airy', 'Bright & Airy', 'camera', '明るく透明感のある、白飛び寸前のエアリーなトーン。',
    { exposure: 0.35, contrast: -0.15, saturation: -0.05, temperature: 0.05, highlights: -0.2, fade: 0.05 },
    ['exposure', 'contrast', 'fade']),
  P('matte_fade', 'Matte Fade', 'camera', '黒を持ち上げたマットな質感。',
    { fade: 0.3, contrast: 0.1, saturation: -0.1 },
    ['fade', 'contrast', 'saturation']),
  P('hdr_punch', 'HDR Punch', 'camera', 'シャドウを持ち上げハイライトを抑えた、ディテール強調のHDR風。',
    { clarity: 0.6, shadows: 0.4, highlights: -0.4, saturation: 0.2, sharpen: 0.4, blurRadius: 0.04 },
    ['clarity', 'shadows', 'highlights', 'sharpen']),
  P('soft_portrait', 'Soft Portrait', 'camera', 'ソフトフォーカスで肌を滑らかに見せるポートレート向け。',
    { glow: 0.3, glowMode: 3, blurRadius: 0.012, temperature: 0.08, exposure: 0.1, saturation: 0.05 },
    ['glow', 'blurRadius', 'temperature', 'exposure']),
  P('cool_morning', 'Cool Morning', 'camera', '青みのある澄んだ朝の空気感。',
    { temperature: -0.2, exposure: 0.1, saturation: 0.05, highTint: [0.0, 0.02, 0.04], contrast: 0.05 },
    ['temperature', 'exposure', 'saturation']),
  P('dark_forest', 'Dark Forest', 'camera', 'ティールグリーンのシャドウとダークなトーン。',
    { shadowTint: [-0.05, 0.04, 0.04], exposure: -0.3, saturation: -0.2, contrast: 0.15, vignette: 0.2 },
    ['splitAmt', 'exposure', 'saturation', 'vignette']),
  P('film_lite', 'Film Lite', 'camera', 'ほんのりフィルム風。フェードと粒子を控えめに。',
    { fade: 0.12, grain: 0.1, saturation: -0.05, temperature: 0.08, contrast: 0.05 },
    ['fade', 'grain', 'temperature']),

  // ---------------- モノクロ (Mono) ----------------
  P('noir', 'Film Noir', 'mono', '高コントラストのモノクロ。赤フィルターで空を落とし周辺減光。',
    { mono: 1, monoMix: [0.6, 0.3, 0.1], contrast: 0.4, vignette: 0.4, grain: 0.15 },
    ['contrast', 'vignette', 'grain']),
  P('hp5', 'Classic BW 400', 'mono', '中庸なトーンの定番モノクロフィルム風。',
    { mono: 1, monoMix: [0.3, 0.55, 0.15], contrast: 0.15, grain: 0.25 },
    ['contrast', 'grain', 'grainSize']),
  P('trix', 'Push BW 1600', 'mono', '増感現像した粗粒子・高コントラストのモノクロ。',
    { mono: 1, monoMix: [0.45, 0.4, 0.15], contrast: 0.35, grain: 0.4, grainSize: 2.2, shadows: -0.1 },
    ['contrast', 'grain', 'grainSize']),
  P('soft_mono', 'Soft Mono', 'mono', '軽やかで明るいモノクロ。フェード気味。',
    { mono: 1, contrast: 0.05, exposure: 0.1, fade: 0.12 },
    ['exposure', 'fade', 'contrast']),
  P('selenium', 'Selenium Tone', 'mono', 'セレン調色風。シャドウにわずかな紫。',
    { mono: 1, contrast: 0.2, shadowTint: [0.03, -0.01, 0.05], grain: 0.1 },
    ['contrast', 'splitAmt', 'grain']),
  P('sepia', 'Sepia', 'mono', 'セピア調色。',
    { mono: 1, contrast: 0.1, shadowTint: [0.05, 0.02, -0.03], highTint: [0.09, 0.05, -0.04], fade: 0.06 },
    ['splitAmt', 'contrast', 'fade']),

  // ---------------- イラスト (Illustration) ----------------
  P('anime_diffusion', 'アニメ塗り ディフュージョン', 'illust',
    '複製→ガウスぼかし→スクリーン合成、不透明度20〜40%の定番手順。レベル補正で明部だけを光らせます。',
    { glow: 0.3, glowMode: 0, blurRadius: 0.02, glowThreshold: 0.3 },
    ['glow', 'blurRadius', 'glowThreshold', 'saturation']),
  P('soft_focus', 'ソフトフォーカス', 'illust',
    'ぼかしたコピーを通常合成で薄く重ねる、柔らかい仕上げ。',
    { glow: 0.35, glowMode: 3, blurRadius: 0.012 },
    ['glow', 'blurRadius']),
  P('glow_strong', 'グロー効果 (強)', 'illust',
    'レベル補正で明部を抽出→大きくぼかす→スクリーン。光源やハイライトが強く輝きます。',
    { glow: 0.55, glowMode: 0, blurRadius: 0.035, glowThreshold: 0.55, contrast: 0.05 },
    ['glow', 'blurRadius', 'glowThreshold', 'contrast']),
  P('add_glow', '加算発光', 'illust',
    '明部を加算(発光)合成で重ねる暖色寄りの発光。逆光・エフェクト表現に。',
    { glow: 0.35, glowMode: 1, blurRadius: 0.03, glowThreshold: 0.6, glowTint: [1.0, 0.9, 0.75] },
    ['glow', 'blurRadius', 'glowThreshold']),
  P('overlay_blur', 'オーバーレイぼかし', 'illust',
    'ぼかしたコピーをオーバーレイで重ね、コントラストと彩度にメリハリを付けます。',
    { glow: 0.3, glowMode: 2, blurRadius: 0.02, glowThreshold: 0 },
    ['glow', 'blurRadius', 'saturation']),
  P('perlin_noise', '薄いノイズ仕上げ (パーリン)', 'illust',
    'パーリンノイズをオーバーレイ・不透明度20〜25%で重ねる仕上げ。画面が整い質感が出ます。',
    { grain: 0.22, grainType: 1, grainSize: 6 },
    ['grain', 'grainSize']),
  P('fine_noise', '細かいノイズ仕上げ', 'illust',
    '細かなランダムノイズをオーバーレイで薄く。デジタル臭さを抑えます。',
    { grain: 0.15, grainType: 0, grainSize: 1.2 },
    ['grain', 'grainSize']),
  P('tairiku', '大陸塗り風仕上げ', 'illust',
    '影は寒色・光は暖色で色相差を付け、高コントラスト・高彩度に。覆い焼き風の発光、色収差、シャープで情報量を増やします。',
    { contrast: 0.25, saturation: 0.2, vibrance: 0.15,
      shadowTint: [-0.06, -0.02, 0.12], highTint: [0.10, 0.05, -0.06],
      glow: 0.25, glowMode: 1, blurRadius: 0.03, glowThreshold: 0.6, glowTint: [1.0, 0.85, 0.7],
      chromAb: 0.35, sharpen: 0.3, clarity: 0.15,
      gmAmt: 0.12, gmDark: [0.08, 0.04, 0.22], gmMid: [0.55, 0.45, 0.5], gmLight: [1.0, 0.93, 0.8] },
    ['splitAmt', 'glow', 'chromAb', 'contrast', 'saturation', 'sharpen', 'gmAmt']),
  P('backlight', '逆光加工', 'illust',
    '明部に暖色の加算発光、影に寒色を足して逆光の空気感を出します。',
    { glow: 0.4, glowMode: 1, blurRadius: 0.05, glowThreshold: 0.55, glowTint: [1.0, 0.8, 0.55],
      shadowTint: [-0.04, 0.0, 0.08], contrast: 0.15, vignette: 0.15 },
    ['glow', 'blurRadius', 'glowThreshold', 'splitAmt', 'contrast']),
  P('rgb_shift', '色収差 (RGBずらし)', 'illust',
    'RGBチャンネルを放射状にずらす、エモさを出す定番の仕上げ。',
    { chromAb: 1.0, sharpen: 0.15 },
    ['chromAb', 'sharpen']),
  P('anime_screenshot', 'アニメスクショ風', 'illust',
    '弱いディフュージョン、色収差、微細ノイズ、周辺減光を組み合わせた映像風。',
    { glow: 0.2, glowMode: 0, blurRadius: 0.025, glowThreshold: 0.35, chromAb: 0.25, sharpen: 0.2,
      grain: 0.06, grainSize: 1.2, contrast: 0.05, vignette: 0.12 },
    ['glow', 'chromAb', 'grain', 'vignette']),
  P('gradmap_warm', 'グラデーションマップ (暖)', 'illust',
    '暗部を紫、明部をクリーム色へ寄せるグラデーションマップを低不透明度で。',
    { gmAmt: 0.3, gmDark: [0.18, 0.06, 0.28], gmMid: [0.6, 0.42, 0.42], gmLight: [1.0, 0.94, 0.82] },
    ['gmAmt', 'saturation', 'contrast']),
  P('gradmap_cool', 'グラデーションマップ (寒)', 'illust',
    '暗部を紺、明部を淡い水色へ寄せる冷たいグラデーションマップ。',
    { gmAmt: 0.3, gmDark: [0.05, 0.08, 0.25], gmMid: [0.4, 0.45, 0.6], gmLight: [0.88, 0.95, 1.0] },
    ['gmAmt', 'saturation', 'contrast']),
  P('thick_paint', '厚塗りマット', 'illust',
    '明瞭度と大きめのノイズで筆致・キャンバス感を足すマットな仕上げ。',
    { clarity: 0.3, saturation: -0.08, contrast: 0.12, grain: 0.14, grainType: 1, grainSize: 3, fade: 0.06, blurRadius: 0.03 },
    ['clarity', 'grain', 'grainSize', 'contrast']),
  P('paper_texture', '紙テクスチャ', 'illust',
    '粗めのノイズと軽いフェードで紙に印刷したような質感。',
    { grain: 0.28, grainType: 1, grainSize: 12, fade: 0.1, saturation: -0.1, exposure: 0.08 },
    ['grain', 'grainSize', 'fade']),
  P('pastel_illust', 'パステル淡色', 'illust',
    '彩度を落とし明るく、フェードで淡いパステル風に。',
    { fade: 0.2, exposure: 0.15, saturation: -0.15, contrast: -0.1, highTint: [0.04, 0.02, 0.03] },
    ['fade', 'exposure', 'saturation']),
];

export const PRESET_MAP = Object.fromEntries(PRESETS.map(p => [p.id, p]));

function lerpVal(a, b, t) {
  if (Array.isArray(a)) return a.map((v, i) => v + (b[i] - v) * t);
  return a + (b - a) * t;
}

/** Compute the parameters actually sent to the engine. */
export function effectiveParams(preset, overrides, intensity, adjust) {
  const merged = { ...NEUTRAL, ...preset.params, ...overrides };
  const out = {};
  for (const k of Object.keys(NEUTRAL)) {
    out[k] = LERP_KEYS.has(k) ? lerpVal(NEUTRAL[k], merged[k], intensity) : merged[k];
  }
  for (const [k, v] of Object.entries(adjust || {})) {
    if (!v) continue;
    const def = CONTROL_DEFS[k];
    const lo = k === 'grain' || k === 'vignette' || k === 'fade' ? 0 : def.min;
    out[k] = Math.min(Math.max(out[k] + v, lo), def.max);
  }
  return out;
}
